import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { APP_NAME } from "../constants/brand";
import { useChatSession } from "../context/ChatSessionContext";
import MessageList from "../components/chat/MessageList";
import ChatInput from "../components/ChatInput";
import ChatHistoryDrawer from "../components/chat/ChatHistoryDrawer";
export default function ChatPage() {
    const [historyOpen, setHistoryOpen] = useState(false);
    const { messages, isLoading, error, skills, selectedSkillRef, setSelectedSkillRef, send, interrupt, userId, currentSessionId, appendUploadedFile, startNewChat, } = useChatSession();
    return (_jsxs("div", { className: "flex flex-col h-full relative", children: [_jsxs("header", { className: "shrink-0 flex items-center justify-end gap-1 px-4 py-2.5 border-b border-ink-100/80 bg-white/60 backdrop-blur-sm", children: [_jsxs("button", { type: "button", onClick: () => startNewChat(), className: "group relative flex items-center justify-center w-10 h-10 rounded-xl text-ink-500 hover:text-brand-700 hover:bg-white hover:shadow-sm transition-all", "aria-label": "\u65B0\u5EFA\u5BF9\u8BDD", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M12 4.5v15m7.5-7.5h-15" }) }), _jsx("span", { className: "nav-tooltip", children: "\u65B0\u5EFA" })] }), _jsxs("button", { type: "button", onClick: () => setHistoryOpen(true), className: "group relative flex items-center justify-center w-10 h-10 rounded-xl text-ink-500 hover:text-brand-700 hover:bg-white hover:shadow-sm transition-all", "aria-label": "\u5386\u53F2\u5BF9\u8BDD", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", strokeWidth: 1.75, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" }) }), _jsx("span", { className: "nav-tooltip", children: "\u5386\u53F2" })] })] }), isLoading && (_jsx("div", { className: "shrink-0 py-2 border-b border-ink-100/80 bg-brand-50/50", children: _jsxs("p", { className: "page-content text-xs text-brand-600 font-medium flex items-center gap-1.5", children: [_jsx("span", { className: "inline-block w-1.5 h-1.5 rounded-full bg-brand-500 animate-pulse" }), APP_NAME, " \u6B63\u5728\u6267\u884C\u2026"] }) })), error && (_jsx("div", { className: "shrink-0 py-2 bg-rose-50 border-b border-rose-100", children: _jsx("p", { className: "page-content text-xs text-rose-600", children: error }) })), _jsx(MessageList, { messages: messages, userId: userId, sessionId: currentSessionId }), _jsx("div", { className: "shrink-0 border-t border-ink-200/60 bg-white/80 backdrop-blur-xl py-4", children: _jsx("div", { className: "page-content", children: _jsx(ChatInput, { skills: skills, selectedSkillRef: selectedSkillRef, onSelectSkill: setSelectedSkillRef, onClearSkill: () => setSelectedSkillRef(""), isLoading: isLoading, onSend: send, onInterrupt: interrupt, userId: userId, sessionId: currentSessionId, onUploaded: appendUploadedFile }) }) }), _jsx(ChatHistoryDrawer, { open: historyOpen, onClose: () => setHistoryOpen(false) })] }));
}
